name: Manual Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - sales
          - sales-staging
          - sales-b

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: mkdir -p path/to/${{ github.event.inputs.environment }}
      - run: echo hello > path/to/${{ github.event.inputs.environment }}.txt
      - name: Display values
        run: |
          ls
  upload-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: path/to/${{ github.event.inputs.environment }}
          retention-days: 90
  download-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R
