name: Manual Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - sales
          - sales-staging
          - sales-b

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create directory
        run: mkdir -p ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}
      - name: Create file
        run: echo hello > ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}/test.txt
      - name: Display values
        run: ls -R ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/path/to/
          retention-days: 90

  download-artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/
