name: Manual Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - sales
          - sales-staging
          - sales-b

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      - name: Set up environment
        run: |
          mkdir -p ${{ github.event.inputs.environment }}/output
      - name: Display values
        run: |
          ls
