name: Manual Action

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The environment to deploy to"
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - sales
          - sales-staging
          - sales-b

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTION_NAME: ""

    steps:
      - name: Check Authorized User
        run: |
          authorized_users="${{ secrets.AUTHORIZED_USERS }}"

          IFS=',' read -ra users <<< "$authorized_users"
          authorized=false

          for user in "${users[@]}"; do
            if [[ "$user" == "${GITHUB_ACTOR}" ]]; then
              authorized=true
              break
            fi
          done

          if [ "$authorized" != true ]; then
            echo "This workflow can only be run by authorized users."
            exit 1
          fi
      - name: Set action_name variable
        run: |
          case "${{ github.event.inputs.environment }}" in
            "prod")
              export ACTION_NAME="Acción 1"
              echo "$ACTION_NAME"
              ;;
            "sales" | "sales-staging" | "sales-b")
              export ACTION_NAME="Otro Nombre de Acción"
              ;;
            *)
              echo "Entorno no reconocido"
              exit 1
              ;;
          esac
      - name: Revisar ejecuciones exitosas de $ACTION_NAME
        run: |
          echo "$ACTION_NAME"
          api_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?&status=success")
            
          last_run_status=$(echo "$api_response" | jq -r ".workflow_runs | sort_by(.created_at) | reverse | .[0] | select(.name == \"$ACTION_NAME\").conclusion")

          echo "Resultado de la API:"
          echo "$last_run_status"

          if [ "$last_run_status" == "success" ]; then
            echo "$ACTION_NAME se ejecutó exitosamente. Puedes ejecutar Acción 2."
          else
            echo "$ACTION_NAME no se ejecutó correctamente o no hay ejecuciones anteriores exitosas. No se ejecutará Acción 2."
            exit 1
          fi

      - name: Create directory
        run: mkdir -p ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}
      - name: Create file
        run: echo hello > ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}/test.txt
      - name: Display values
        run: ls -R ${{ github.workspace }}/path/to/${{ github.event.inputs.environment }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: ${{ github.workspace }}/path/to/
          retention-days: 90
      - name: Set output variable
        id: set-output
        run: echo "::set-output name=artifact_name::my-artifact"
# La variable github.actor en GitHub Actions te da el nombre del usuario
# que está activando el flujo de trabajo. Sin embargo, no necesitas
# definir explícitamente quiénes son los "authorized users" en el código
# del flujo de trabajo. Más bien, debes configurar las restricciones en
# la configuración de tu repositorio o en tu organización.

# GitHub Actions proporciona configuraciones a nivel de repositorio y
# organización para controlar quién puede ejecutar ciertos flujos de trabajo.
# Puedes configurar estas restricciones en la configuración del repositorio o en la configuración de tu organización.

# Para restringir el acceso a nivel de repositorio:

# En tu repositorio, haz clic en la pestaña "Settings".
# En el menú lateral, selecciona "Actions".
# En la sección "Workflow permissions", puedes especificar las restricciones de ejecución del flujo de trabajo.
# Por ejemplo, puedes agregar un patrón de rama o de evento que indique cuándo
# se permite ejecutar el flujo de trabajo. Puedes utilizar esta funcionalidad para
# controlar quién puede activar el flujo de trabajo basándote en patrones específicos.

# Para restringir el acceso a nivel de organización:

# Si estás trabajando en una organización, ve al panel de configuración de la organización.
# En el menú lateral, selecciona "Settings".
# En "Member privileges", busca la sección de "Actions".
# Configura las restricciones de ejecución del flujo de trabajo según tus necesidades.

# Esto te permitirá controlar quién puede activar flujos de trabajo en tu repositorio u organización.

# Recuerda que estas configuraciones de permisos se deben establecer en el nivel de GitHub y no en el archivo YAML del flujo de trabajo.
