name: Manual Action

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          mkdir -p ${{ github.workspace }}/output

      - name: Manual input
        run: |
          echo "¿Qué valores deseas ingresar?"
          read -p "Valor 1: " value1
          read -p "Valor 2: " value2
          read -p "Valor 3: " value3

          echo "Valor 1: $value1" > ${{ github.workspace }}/output/values.txt
          echo "Valor 2: $value2" >> ${{ github.workspace }}/output/values.txt
          echo "Valor 3: $value3" >> ${{ github.workspace }}/output/values.txt

      - name: Display values
        run: |
          cat ${{ github.workspace }}/output/values.txt
