name: Consume Artifact

on:
  workflow_dispatch:

jobs:
  consume-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ needs.produce-artifact.outputs.artifact_name }}
          path: path/to/destination
