name: Acción 2

on:
  workflow_dispatch:
    inputs:
      run-action2:
        description: 'Ejecutar Acción 2'

jobs:
  job2:
    runs-on: ubuntu-latest

    steps:
      - name: Verificar ejecución de Acción 1
        run: |
          api_response=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs?&status=success")
            

            # Obtener la fecha hace 14 días en formato ISO 8601
            date_14_days_ago=$(date -u -d "14 days ago" +"%Y-%m-%dT%H:%M:%SZ")

            # Obtener la última conclusión de la "Acción 1" y su marca de tiempo de creación
            last_run=$(echo "$api_response" | jq -r '.workflow_runs | sort_by(.created_at) | reverse | .[] | select(.name == "Acción 1")' | head -n 1)
            last_run_status=$(echo "$last_run" | jq -r '.conclusion')
            last_run_created_at=$(echo "$last_run" | jq -r '.created_at')

            # Verificar si la última ejecución ocurrió dentro de los últimos 14 días
            if [ "$last_run_status" == "success" ] && [ "$last_run_created_at" \> "$date_14_days_ago" ]; then
                echo "La última ejecución exitosa de Acción 1 ocurrió dentro de los últimos 14 días. Puedes ejecutar Acción 2."
            else
                echo "No hay ejecuciones exitosas de Acción 1 en los últimos 14 días. No se ejecutará Acción 2."
                exit 1
            fi
