name: Auto Workflow

on:
  push:
    branches:
      - main

jobs:
  auto-job:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Job Step
        run: echo "This is the auto job, runs on every push."

