name: Auto and Manual Workflow

on:
  push:
    branches:
      - main

jobs:
  auto-job:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Job Step
        run: echo "This is the auto job, runs on every push."

  manual-job:
    runs-on: ubuntu-latest
    needs: auto-job
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Manual Job Step
        run: echo "This is the manual job, runs manually."

